### ISSUE TITLE
Addition to toolbar, key-binds and toggling

### ISSUE THREAD

**Issue by ty5e3a45** [TheNamlessGuy/browser-redirector#1]
Hey, been using the extension for about 2 months and I love it.
I was wondering if you had any plans for allowing extension to be added to toolbar with an option to toggle on/off the redirects, or to have it be possible through a custom key-bind?
Every now and then I need to turn off one of the redirects, and having to go in settings and manually deactivate the extension, or the specific redirect area is annoying.
Looking forward to updates, and thanks again.

**Comment by TheNamlessGuy** [comment]
I don't have a lot of spare time at the moment, but it seems reasonable. I'll get around to it eventually.

**Comment by TheNamlessGuy** [comment]
Version 0.5.0 should have a browser action with which you can toggle active status of redirects.

Browser actions are the things listed behind the puzzle piece by the address bar, if you didn't know.
