### ISSUE TITLE
issue with reddit redirect and image files

### ISSUE THREAD

**Issue by lazymonkey2** [TheNamlessGuy/browser-redirector#4]
Hello, I want to redirect all www.reddit.com to new.reddit.com (because I don't like the new page design).
I've tried this config:
From:
^(http|https)://www\.reddit\.com(.*)
To:
{{1}}://new.reddit.com{{2}}
And it seems to work, except when I click on an image, like this:
https://new.reddit.com/r/firefox/comments/1anc5w2/comment/kq1yvom/
When I click the image I get an infinite reload loop.
Is it possible to change the config to avoid this? Or is it a bug in the extension?
Thanks.

**Comment by lazymonkey2** [comment]
hello, thanks for answering.

I tried to implement your second suggestion, that don't requires to change the extension.

From my tests the url that should not be redirected is this one:
https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fnot-used-firefox-consumes-more-battery-than-every-other-app-v0-3kjszcs6w3ic1.jpeg%3Fwidth%3D1080%26format%3Dpjpg%26auto%3Dwebp%26s%3D86a59e3dda5e13a01cd85b0a90f704c15332ffa6

I don't understand why you are talking about this url instead:
https://new.reddit.com/r/firefox/comments/1anc5w2/comment/kq1yvom/

Anyway I was trying to exclude the /media?url=
using this re:
^(http|https)://www\.reddit\.com(?!\/media?url=)

but then I got stuck.
Do you have any suggestion?

Thanks.

**Comment by TheNamlessGuy** [comment]
I can't really help you with the regex part, sadly. You could try [^(/media)] or something of the sort.

**Comment by lazymonkey2** [comment]
ok I'll try your suggestion. thank you.
