### ISSUE TITLE
Function request: URL encoding/decoding

### ISSUE THREAD

**Issue by MagicalDrizzle** [TheNamlessGuy/browser-redirector#5]
I use redirector to redirect doi links to sci-hub to read scientific papers. However, the service happen to URL-encode the doi to point at the pdf file.
For example:
`https://doi.org/10.1890/0012-9658(2002)083[1386:LHSSIB]2.0.co;2`
turn into: 
`10.1890/0012-9658%25282002%2529083%255B1386%253ALHSSIB%255D2.0.CO%253B2`
Anything after `10\.[0-9]{2,9}\/` will be URL-encoded.
I'd love for there to be a function to accomplish this redirection.

**Comment by TheNamlessGuy** [comment]
Done and done 👍
